# makefile for lutf8lib

PKGNAME=lutf8lib
SRC=$(PKGNAME).c
OBJ=$(PKGNAME).o
DYNLIB=$(MYNAME).so

INCS= -I$(LUA)/include
WARN= #-ansi -pedantic -Wall
CFLAGS= $(INCS) $(DEFS) $(WARN) -O2 $G -fPIC

$(DYNLIB): $(OBJ)
	$(CC) $(MYLDFLAGS) -o $@ $(OBJ)

$(OBJ): $(SRC)
	$(CC) $(CFLAGS) -c -o $@ $(SRC)

clean:
	rm -f $(OBJ) $(DYNLIB)
