# makefile for lua fribidi wrapper

PKGNAME=lua_fribidi_wrapper
SRC=$(PKGNAME).c
OBJ=$(PKGNAME).o
DYNLIB=$(MYNAME).so

INCS= -I$(LUA)/include -I$(LUA)/include/fribidi
LIBS= -lfribidi
WARN= #-ansi -pedantic -Wall
CFLAGS= $(INCS) $(DEFS) $(WARN) -O2 $G -fPIC

$(DYNLIB): $(OBJ)
	$(CC) $(MYLDFLAGS) -o $@ $(OBJ) $(LIBS)

$(OBJ): $(SRC)
	$(CC) $(CFLAGS) -c -o $@ $(SRC)

clean:
	rm -f $(OBJ) $(DYNLIB)
